version: '2.1'
services:
  proxy:
    image: pdok/wmts-kvp-to-restful
    restart: unless-stopped      
    command: ["wmts-kvp-to-restful", "-host=http://mapproxy:80","-t=./config/WMTSCapabilities.template.xml","-l=true"]
    ports:
      - "9001:9001"
    volumes:
      - ./config:/config
    networks:
      proxy-network:
  mapproxy:
    image: pdok/mapproxy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DEBUG=1
    volumes:
      - ./config/mapproxy.yaml:/srv/mapproxy/config/mapproxy.yaml
    networks:
      proxy-network:
networks:
  proxy-network: